### 1. 什么是变量

In [1]:
print(245)
print(2.24)
print('这是一个字符串')

245
2.24
这是一个字符串


In [9]:
a = 1
b = 4.2
c = 'abc'
d = [1,2,3,4]
print(a,b,c,d)
print(type(a), type(b), type(c), type(d))
print(id(a), id(b), id(c), id(d))

1 4.2 abc [1, 2, 3, 4]
<class 'int'> <class 'float'> <class 'str'> <class 'list'>
140707917378384 1839550161496 1839506126416 1839552176584


In [16]:
a = 1
print(a, type(a), id(a))
a = 'hello world'
print(a, type(a), id(a))

1 <class 'int'> 140707917378384
hello world <class 'str'> 1839553793072


In [18]:
# 多变量赋值
a = b = c = 1
print(a, b, c)
print(id(a), id(b), id(c))
a, b, c = 1, 2, 3
print(a, b, c)
print(id(a), id(b), id(c))

1 1 1
140707917378384 140707917378384 140707917378384
1 2 3
140707917378384 140707917378416 140707917378448


In [19]:
# 注意值的指向
a = 1
b = 1.0
print(id(a), id(b))
# is 判断两个指的是不是同一个内存地址
print(a is b)
print(a == b)

140707917378384 1839550162456
False
True


In [21]:
a = 1
b = 1
print(id(a), id(b))
print(a is b)

140707917378384 140707917378384
True


### 2.基本数据类型

In [22]:
type(10)

int

In [23]:
type(10.1)

float

In [24]:
a = 100
b = 17
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a ** b)
print(a % b)

117
83
1700
5.882352941176471
5
10000000000000000000000000000000000
15


In [25]:
print(1 > 2)
print(1 < 2)
print(1 == 2)
print(1 != 2)
print(1 >= 2)
print(1 <= 2)

False
True
False
True
False
True


In [38]:
False == bool(0)

True

In [39]:
print('a,b,c')

a,b,c


In [40]:
print('a,\nb\n,c')

a,
b
,c


In [42]:
# 路径设置
dir1 = 'C:/Users/Desktop/'
dir2 = 'C:\\Users\\Desktop\\'
print(dir1)
print(dir2)

C:/Users/Desktop/
C:\Users\Desktop\


In [43]:
# 字符串运算
print('hello ' + 'world')
print('hello ' * 3)
print('h' in 'hello', 'h' not in 'hello')

hello world
hello hello hello 
True False


In [50]:
# 字符串常用方法、函数
print(len('123456'))
print(str(12345), str(10.29))
print(int('12345'), float('2008.12'))
# eval() 执行字符串的内容
print(eval('100*20'))
print(eval('123'), type(eval('123')))

var1 = 'hello world'
print(var1.replace('l', 'L'))

var2 = "小明， 男， 设计师"
print(var2.split('，'))


6
12345 10.29
12345 2008.12
2000
123 <class 'int'>
heLLo worLd
['小明', ' 男', ' 设计师']


In [53]:
# 格式化字符串
var1 = 10
var2 = 89.9365
var3 = '城市数据团'
print('这个班上一共有%i人' % var1)
print('小明这次考了%f分' % var2)
print('小明这次考了%.2f分' % var2)
print('听说%s很6' % var3)

print('这个班上一共有%i人, 小明这次考了%.2f分, 听说%s很6' %(var1, var2, var3))

这个班上一共有10人
小明这次考了89.936500分
小明这次考了89.94分
听说城市数据团很6
这个班上一共有10人, 小明这次考了89.94分, 听说城市数据团很6


In [54]:
# 序列 分为： 元组、列表、字符串
# 列表
lst1 = [1,2,3,4,5,6]
lst2 = ['a', 'b', 'c', 'd']
lst3 = ['abc', 123, 10.2, [1,2,3,4]]
print(lst1)
print(lst2)
print(lst3)
print('这是一个列表：', lst1)


[1, 2, 3, 4, 5, 6]
['a', 'b', 'c', 'd']
['abc', 123, 10.2, [1, 2, 3, 4]]
这是一个列表： [1, 2, 3, 4, 5, 6]


In [55]:
# 列表运算
print([1,2,3]+[4,5,6])
print([1,2,3]*3)
print(5 in [2,3,4])
print(len(lst3))

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
False
4


In [56]:
# 索引
lst = [1,2,3,4,5,[1,2,3,4]]
print(lst)
print(lst[0], lst[1])
print(lst[-1], lst[-2])

[1, 2, 3, 4, 5, [1, 2, 3, 4]]
1 2
[1, 2, 3, 4] 5


In [57]:
for index, value in enumerate(lst):
    print(index, value)

0 1
1 2
2 3
3 4
4 5
5 [1, 2, 3, 4]


In [58]:
st = 'hello world'
print(st[0], st[1], st[-1])

h e d


In [62]:
# 切片 左闭右开
print(lst)
print(lst[2:3])
print(lst[:2])
print(lst[1:])
print(lst[1:-1])
print(st[1:])

print(st[:-2])

[1, 2, 3, 4, 5, [1, 2, 3, 4]]
[3]
[1, 2]
[2, 3, 4, 5, [1, 2, 3, 4]]
[2, 3, 4, 5]
ello world
hello wor


In [67]:
# 列表的常用方法
lst = [10,20,30,40,50,60,70,80,90]
print(len(lst))

lst.append(100)
lst.extend(['a', 'b'])
lst.extend([['a','b']])
print(lst)
print('---'*4)

lst.insert(2,1000)
print(lst)
print('---'*4)

lst2 = lst
lst3 = lst.copy()
print(lst, id(lst))
print(lst2, id(lst2))
print(lst3, id(lst3))

9
[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 'a', 'b', ['a', 'b']]
------------
[10, 20, 1000, 30, 40, 50, 60, 70, 80, 90, 100, 'a', 'b', ['a', 'b']]
------------
[10, 20, 1000, 30, 40, 50, 60, 70, 80, 90, 100, 'a', 'b', ['a', 'b']] 1839554699144
[10, 20, 1000, 30, 40, 50, 60, 70, 80, 90, 100, 'a', 'b', ['a', 'b']] 1839554699144
[10, 20, 1000, 30, 40, 50, 60, 70, 80, 90, 100, 'a', 'b', ['a', 'b']] 1839556624264


### 3.模块导入

### 4. numpy、pandas数据类型

In [68]:
import numpy as np
import pandas as pd

In [72]:
ar = np.array([1,2,3,4,5,6,7])
print(ar)
print(ar.ndim)
print(ar.shape)
print(ar.size)
print(ar.dtype)
print(ar.itemsize)
print(ar.data)

[1 2 3 4 5 6 7]
1
(7,)
7
int32
4


In [76]:
lst = [1,2,3,4,5,6]
print(lst, type(lst))

ar = np.array([lst, lst])
print(ar, type(ar))

[1, 2, 3, 4, 5, 6] <class 'list'>
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]] <class 'numpy.ndarray'>


In [79]:
ar1 = np.arange(10)
ar2 = np.ones((5,2))
print(ar1,'\n',ar1.T)
print(ar2,'\n',ar2.T)

[0 1 2 3 4 5 6 7 8 9] 
 [0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [81]:
ar3 = ar1.reshape(2,5)
ar4 = np.zeros((4,6)).reshape(3,8)
ar5 = np.reshape(np.arange(12),(3,4))
print(ar1, '\n', ar3)
print(ar4)
print(ar5)

[0 1 2 3 4 5 6 7 8 9] 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [92]:
# 基本索引及切片
# 一维数组索引及切片
ar = np.arange(20)
print(ar)
print(ar[4])
print(ar[3:6])
print('--------')

# 二维数组索引及切片
ar = np.arange(16).reshape(4,4)
print(ar, '数组轴数为%i' %ar.ndim)
print(ar[2], '数组轴数为%i' %ar[2].ndim)
print(ar[2][1])
print(ar[1:3])
print(ar[2,2])
print(ar[:2,1:])
print('-------------')
# 三维数组索引及切片
ar = np.arange(8).reshape(2,2,2)
print(ar, '数组的轴数为%i' %ar.ndim)
print(ar[0])
print(ar[0][0])
print(ar[0][0][1])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
4
[3 4 5]
--------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 数组轴数为2
[ 8  9 10 11] 数组轴数为1
9
[[ 4  5  6  7]
 [ 8  9 10 11]]
10
[[1 2 3]
 [5 6 7]]
-------------
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 数组的轴数为3
[[0 1]
 [2 3]]
[0 1]
1


In [94]:
# Dataframe
ar = np.arange(10).reshape(5,2)
ar

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [95]:
df = pd.DataFrame(np.arange(10).reshape(5,2), columns=['A', 'B'])
df

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

In [96]:
# Dataframe 数据结构
# Dataframe 是一个表格型的数据结构， “带有标签的二维数组”
# Dataframe 带有index（行标签）和 columns（列标签）

In [99]:
df = pd.DataFrame(np.random.rand(12).reshape(3,4)*100,
                  index=['one', 'two', 'three'],
                  columns=['a', 'b', 'c', 'd']
                 )
print(df)
print(type(df))
print('---'*3)
print(df.index, type(df.index))
print(df.columns, type(df.columns))
print(df.values, type(df.values))

               a          b          c          d
one    78.697056  30.949900  23.720975  83.449117
two     4.911191  36.064800  92.206459  96.554411
three  71.185992  91.356109  13.431242  88.906149
<class 'pandas.core.frame.DataFrame'>
---------
Index(['one', 'two', 'three'], dtype='object') <class 'pandas.core.indexes.base.Index'>
Index(['a', 'b', 'c', 'd'], dtype='object') <class 'pandas.core.indexes.base.Index'>
[[78.69705612 30.94989961 23.72097534 83.4491174 ]
 [ 4.91119104 36.0647999  92.2064589  96.55441124]
 [71.18599177 91.35610904 13.43124217 88.90614885]] <class 'numpy.ndarray'>


In [102]:
df

a          b          c          d
one    78.697056  30.949900  23.720975  83.449117
two     4.911191  36.064800  92.206459  96.554411
three  71.185992  91.356109  13.431242  88.906149

In [100]:
# 在dataframe 中分列索引和行索引
# 列索引: df[]
print(df['a'])          # 单列索引，结果为Series
print(df[['a']])        # 单列索引，结果为DataFrame
print(df[['a', 'c']])   # 多列索引，结果为DataFrame

one      78.697056
two       4.911191
three    71.185992
Name: a, dtype: float64
               a
one    78.697056
two     4.911191
three  71.185992
               a          c
one    78.697056  23.720975
two     4.911191  92.206459
three  71.185992  13.431242


In [103]:
# 行索引 df.loc[]切片末端包含  - 按index选择行 df.iloc[]切片末端不包含
df1 = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index= ['one','two','three','four'],
                   columns = ['a','b','c','d']
                  )
df1

a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
two    48.351678  99.781819  47.577657  76.304618
three   2.261258  89.544249  50.279505  48.789906
four   29.798335  35.365883  81.129231  99.313109

In [107]:
data1 = df1.loc['one']
print(data1)
print('单行(单标签)索引\n')
data2 = df1.loc[['one','three','four']]
print(data2)
print('多标签索引\n')

data3 = df1.loc['one':'three']
print(data3)
print('切片索引')

a    92.246705
b    30.664009
c    89.310805
d    59.109763
Name: one, dtype: float64
单行(单标签)索引

               a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
three   2.261258  89.544249  50.279505  48.789906
four   29.798335  35.365883  81.129231  99.313109
多标签索引

               a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
two    48.351678  99.781819  47.577657  76.304618
three   2.261258  89.544249  50.279505  48.789906
切片索引


In [109]:
df1

a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
two    48.351678  99.781819  47.577657  76.304618
three   2.261258  89.544249  50.279505  48.789906
four   29.798335  35.365883  81.129231  99.313109

In [114]:
print(df1.iloc[0])
print(df1.iloc[-1])
print('单位置索引')
print(df1.iloc[[0,2]])
print(df1.iloc[[3,2,1]])
print('多位置索引, 顺序可变')
print(df1.iloc[1:3])
print(df1.iloc[::2])
print('切片索引， 末端不包含')

a    92.246705
b    30.664009
c    89.310805
d    59.109763
Name: one, dtype: float64
a    29.798335
b    35.365883
c    81.129231
d    99.313109
Name: four, dtype: float64
单位置索引
               a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
three   2.261258  89.544249  50.279505  48.789906
               a          b          c          d
four   29.798335  35.365883  81.129231  99.313109
three   2.261258  89.544249  50.279505  48.789906
two    48.351678  99.781819  47.577657  76.304618
多位置索引, 顺序可变
               a          b          c          d
two    48.351678  99.781819  47.577657  76.304618
three   2.261258  89.544249  50.279505  48.789906
               a          b          c          d
one    92.246705  30.664009  89.310805  59.109763
three   2.261258  89.544249  50.279505  48.789906
切片索引， 末端不包含
